### ISSUE TITLE
Camera service Exception !!!

### ISSUE THREAD

**Issue by e2com** [nerdgrlapps/spyapp#1]
01-18 22:22:17.311 12331-15236/? W/System.err:     at org.nerdgrl.spycamera.CameraManager$1.doInBackground(CameraManager.java:43)
01-18 22:22:17.311 12331-15236/? W/System.err:     at org.nerdgrl.spycamera.CameraManager$1.doInBackground(CameraManager.java:36)
01-18 22:22:17.311 12331-15236/? E/CameraManager: Cannot open camera >>> java.lang.RuntimeException: Fail to connect to camera service
----------------------------------------------------------------------
Related source is saved as image file below.
What should I do in this case?
Thank you !!!

![default](https://cloud.githubusercontent.com/assets/3252206/22065760/02ab63f6-ddcd-11e6-8842-71588c4dab3b.JPG)

**Comment by shubham08gupta** [comment]
Try checking if you have camera permission or not. This example works only if you have already Camera permission.
